// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfGcEeE5BswENp8NmYInQYaz5Im_8I3VI',
    appId: '1:868032773881:android:c2a89bdf5cc4d86f26ac28',
    messagingSenderId: '868032773881',
    projectId: 'lettutor-94469',
    storageBucket: 'lettutor-94469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyMrBSSNF3y4s7Rs-0XYNvnIFiOpFKWsQ',
    appId: '1:868032773881:ios:2e94e316b6282f8326ac28',
    messagingSenderId: '868032773881',
    projectId: 'lettutor-94469',
    storageBucket: 'lettutor-94469.appspot.com',
    androidClientId:
        '868032773881-ccssabifm9caek5mjtoros2q344uve5a.apps.googleusercontent.com',
    iosClientId:
        '868032773881-h4dutdhomjnb179u6vvfdul5p03npeoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.beatifulUi.wao',
  );
}
